version: 2.1

executors:
  default:
    working_directory: /tmp/work-dir
    docker:
      - image: orda/ci-base:node-12-1.6.6
    environment:
      JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

workflows:
  version: 2
  react-time-sync:
    jobs:
      - build
      - release:
          context: Semantic-Release
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-react-time-sync-{{ checksum "yarn.lock" }}
            - v1-react-time-sync-
      - run: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-react-time-sync-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn build
      - persist_to_workspace:
          root: "/tmp"
          paths:
            - work-dir
      - run:
          name: Tests
          command: yarn test-ci
          environment:
            TZ: Europe/Berlin
      - store_test_results:
          path: reports/junit
  release:
    executor: default
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Semantic release
          command: yarn release
